### ISSUE TITLE
How hard would it be to get this to work with AWS S3?

### ISSUE THREAD

**Issue by johnloringpollard** [fnix/activestorage-resumable#1]
We would love this functionality but use S3 for our cloud storage.

**Comment by kdiogenes** [comment]
I think that the most difficult aspects are:

* A browser JS that does the hard work of uploading the file to S3, for GCS we use https://github.com/fnix/gcs-browser-upload
* Implements a blob uploader that uses this JS and respects the [resumable_upload.js](https://github.com/fnix/activestorage-resumable/blob/master/app/javascript/activestorage-resumable/resumable_upload.js) API. The GCS blob uploader is implemented in [resumable_blob_upload.js](https://github.com/fnix/activestorage-resumable/blob/master/app/javascript/activestorage-resumable/resumable_blob_upload.js) if you want to take a look.

In addition, you must generate an upload URL, but this is usually simple. Take a look at [gcs_service.rb](https://github.com/fnix/activestorage-resumable/blob/master/lib/activestorage_extensions/service/gcs_service.rb)
